apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-annotation
  labels:
    team: product
    version: 1.4.5
    environment: dev
  annotations:
    description: Ini adalah aplikasi yang dibuat tim product
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
